version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nameswipe
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeMe123}
      POSTGRES_DB: nameswipe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nameswipe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nameswipe"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://nameswipe:${DB_PASSWORD:-changeMe123}@postgres:5432/nameswipe
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nameswipe
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-sites:/etc/nginx/sites-enabled:ro
      - ssl_certs:/etc/letsencrypt
      - ssl_challenge:/var/www/certbot
    depends_on:
      - app
    networks:
      - nameswipe

volumes:
  postgres_data:
  ssl_certs:
  ssl_challenge:

networks:
  nameswipe:
    driver: bridge